/**
 * Runtime generator — assembles a single self-contained ES module (the
 * Cloudflare Worker) from the manifest plus the core/providers/entry
 * sources.
 *
 * Strategy: the runtime sources are plain-JavaScript modules written to be
 * "bundle-safe": their exported symbols are the only cross-file references,
 * so we can strip import/export syntax and concatenate. They are authored as
 * `.js` (not `.ts`) because the Cloudflare script-upload API does NOT
 * transpile TypeScript — the generated worker must be valid ECMAScript
 * byte-for-byte. The manifest (non-secret only) is injected as a JSON literal.
 *
 * Provider secrets are NEVER embedded — the runtime reads them via env.*.
 */

import type { SignerManifest } from '../manifest';

import coreSource from './core.js?raw';
import providersSource from './providers.js?raw';
import entrySource from './entry.js?raw';

/** Strip `import ...;` statements (single- and multi-line). */
function stripImports(src: string): string {
  // Remove multi-line import blocks first.
  let out = src.replace(/import\s+(?:type\s+)?\{[^}]*\}\s+from\s+['"][^'"]+['"];/g, '');
  // Remove single-line imports (side-effect, default, namespace).
  out = out.replace(/^\s*import\s+[^;]*;\s*$/gm, '');
  // Remove `declare const MANIFEST ...;` (we inject the real const).
  out = out.replace(/declare\s+const\s+MANIFEST[^;]*;/g, '');
  return out;
}

/** Convert exported declarations into plain top-level declarations. */
function stripExports(src: string): string {
  return src
    .replace(/export\s+default\s+/g, 'const __default_export__ = ')
    .replace(/export\s+(?=(async\s+)?(function|const|let|class|interface|type)\b)/g, '')
    .replace(/export\s*\{[^}]*\};?/g, '');
}

/**
 * Build the Worker module source for a manifest.
 * @param manifest  Validated, non-secret manifest.
 * @param compatibilityDate  Cloudflare compatibility_date to target.
 */
export function buildWorkerSource(
  manifest: SignerManifest,
  compatibilityDate = '2026-08-01',
): string {
  const core = stripExports(stripImports(coreSource));
  const providers = stripExports(stripImports(providersSource));

  // Entry: keep the default-export handler, but bind it as `__worker`.
  let entry = stripExports(stripImports(entrySource));
  // entry.js used `export default { async fetch ... }` which stripExports
  // turned into `const __default_export__ = { ... }`. Rename for clarity.
  entry = entry.replace('const __default_export__ =', 'const __worker =');

  const manifestJson = JSON.stringify(manifest, null, 2);

  return `/**
 * ${manifest.app} — generated by LEEF Trader Signer (runtime v${manifest.runtimeVersion}).
 *
 * DO NOT EDIT BY HAND. This file is generated from a non-secret manifest.
 * Provider credentials are NOT in this file — they are Cloudflare Worker
 * Secrets read at runtime via env.*.
 */
'use strict';

/* ===== runtime/core ===== */
${core}

/* ===== runtime/providers ===== */
${providers}

/* ===== manifest (non-secret) ===== */
const MANIFEST = ${manifestJson};

/* ===== runtime/entry ===== */
${entry}

export default __worker;

/* compatibility_date: ${compatibilityDate} */
`;
}

/** Extract the compatibility_date we tag at the bottom (for reference). */
export const DEFAULT_COMPATIBILITY_DATE = '2026-08-01';
